### PR TITLE
Refine table

### PR DESCRIPTION
**Pull request by tinaClin**
- Remove calculation functions that access to DOM elements.
- Replacing mini-store with context api.
- Remove element resize detector.
- Update example with styleguide.
- Update properties
   - Table
      - Remove justified, title, footer.
      - Rename showHeader to hideHeader.
      - Add selectedRowKeys, width (required)
      - Change default value of bordered, hideHeader and hoverable to false.
   - Column
      - Remove dataIndex, which is replaced with dataKey.
      - Remove key, className, style, headerClassName, headerStyle, cellClassName, cellStyle, fixed, sortable.

### CODE REVIEW

**Comment by roth1002** [comment]
先給 v2.0.0-alpha.1之類的版本吧

**Comment by roth1002** [comment]
Resolved #24

**Comment by tinaClin** [comment]
About #10, the "justified" prop will be removed in this PR, so the issue is resolved.

**Comment by roth1002** [comment]
Fixed Column 消失了......敲碗

**Comment by tinaClin** [comment]
> Fixed Column 消失了......敲碗

已加example
image

**Review by roth1002 — APPROVED** [review]

**Pull request merged**
